name: Build Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        default: xxx

jobs:
  build-be:
    name: Build Backend
    runs-on: ubuntu-20.04
    steps:
      - name: git clone
        run: git clone --depth 1 --no-tags --branch ${{ github.event.inputs.branch }} https://git.azyobuzi.net/xxx/pleroma.git
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: pleroma
          tags: xxx-be
          outputs: type=docker,dest=be-image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: actions/upload-artifact@v2
        with:
          name: be
          path: be-image.tar
          if-no-files-found: error

  build-fe:
    name: Build Frontend
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: production
    steps:
      - name: git clone
        run: git clone --depth 1 --no-tags --branch ${{ github.event.inputs.branch }} https://git.azyobuzi.net/xxx/pleroma-fe.git
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: pleroma-fe/yarn.lock
      - name: yarn install
        run: yarn install --frozen-lockfile --production=false
        working-directory: pleroma-fe
      - name: yarn build
        run: yarn build
        working-directory: pleroma-fe
      - uses: actions/upload-artifact@v3
        with:
          name: fe
          path: pleroma-fe/dist
          if-no-files-found: error

  build-image:
    name: Build Image
    needs: [build-be, build-fe]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: azyobuzin
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker load
        run: docker load -i be/be-image.tar && rm -rf be
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          push: true
          tags: azyobuzin/pleroma:${{ github.event.inputs.branch }}
